# Archlinux
# Build Vinyl from release tag and publish .zst package
name: archlinux
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      repository:
        required: true
        type: string
      package_name:
        required: true
        type: string
env:
  PKGBUILD: $GITHUB_WORKSPACE/.github/assets/archlinux/PKGBUILD.template
  BUILD_DIR: /var/tmp/build
jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          sparse-checkout: .github/assets/archlinux
          sparse-checkout-cone-mode: false
      - name: Initialize pacman-key
        run: pacman-key --init
      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install additional packages
        run: |
          # base-devel includes build dependencies (fakeroot, make, gcc, pkgconf)
          pacman -Syq base-devel git --noconfirm
      - name: Set parallel makeflags
        run: sed -i 's/.*MAKEFLAGS=.*/MAKEFLAGS="-j $(nproc)"/' /etc/makepkg.conf
      - name: Setup build user
        run: |
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - name: Update PKGBUILD file with new checksum and git tag values
        run: |
          # update tag with latest version
          mkdir ${{ env.BUILD_DIR }}
          cp ${{ env.PKGBUILD }} ${{ env.BUILD_DIR }}/PKGBUILD
          sed -i 's/${version}/'${{ inputs.version }}'/' ${{ env.BUILD_DIR }}/PKGBUILD
          sed -i 's|${repository}|'${{ inputs.repository }}'|' ${{ env.BUILD_DIR }}/PKGBUILD
          sed -i 's/${pkgname}/'${{ inputs.package_name }}'/' ${{ env.BUILD_DIR }}/PKGBUILD
          sha256sum_vinyl=$(curl -Ls ${{ inputs.repository }}/archive/refs/tags/v${{ inputs.version }}.tar.gz | sha256sum | awk {'print $1'})
          sed -i 's/${sha256sums}/'${sha256sum_vinyl}'/' ${{ env.BUILD_DIR }}/PKGBUILD
      - name: Change permissions of build directory
        run: |
          chown builduser:builduser -R ${{ env.BUILD_DIR }}
      - name: Build package
        run: |
          sudo -u builduser bash -c 'cd ${{ env.BUILD_DIR }}; makepkg -s --noconfirm'
          zst_file=$(find ${{ env.BUILD_DIR }} -name "*.zst*")
          publish_filename=vinyl-theme-${{ inputs.version }}-x86_64.pkg.zst
          mv "$zst_file" $GITHUB_WORKSPACE/$publish_filename
          echo "ARTIFACT=$publish_filename" >> "$GITHUB_ENV"
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
          retention-days: 1
